# Use the official Python image from the Docker Hub
FROM python:3.12-bookworm
# Set the working directory in the container
WORKDIR /app
# Copy the current directory contents into the container at /app
COPY . /app
# Run the Python script when the container launches
CMD ["python", "sleep_script.py"]
